编写代码的时候错误大多数是编译错误(语法、类型、格式)等，但是很多错误是运行期才发生的，比如读取文件的时候文件不存在、或者访问切片的时候超过了切片最大的容量，又或者对 nil 的对象进行了操作。

回顾一下前面 defer 章节打开文件的代码:

```go
func read() {
  file, err := os.Open("/tmp/test")
  if err != nil {
    fmt.Printf("%s\n", err)
  }
  file.Close()
}
```

os.Open 函数返回了两个值，一个文件对象，一个错误对象，F12 看看它的函数签名:

```go
// Open opens the named file for reading. If successful, methods on
// the returned file can be used for reading; the associated file
// descriptor has mode O_RDONLY.
// If there is an error, it will be of type *PathError.
func Open(name string) (*File, error) {
  return OpenFile(name, O_RDONLY, 0)
}
```

go 语言通常以最后一个参数来表示调用的错误信息，这种错误是编码的时候预知的。如上，如果文件能被顺利的打开，则返回的第二个值 error 对象是 nil，否则是一个 PathError 对象:

```go
// PathError records an error and the operation and file path that caused it.
type PathError struct {
  Op   string
  Path string
  Err  error
}
```

PathError 是一个包含三个字段的结构体，Op 表示操作类型、Path 表示文件路径，最后一个 Err 是 error 对象，继续看 F12 看 error 的申明:

```go
// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface {
  Error() string
}
```

是一个接口对象，前面提到过 go 里面表示世间万物的是 interface{} 空接口，error 不是空接口，它只有一个行为 Error() 函数，就是报告一行错误信息。这个库函数告诉我们，在能预估错误的情况，可以包装一个 error 对象返回给调用者，由调用者决定下一步的行为:

```go
func exchangeCommand(cmd string) (string, error) {
  if len(cmd) == 0 {
    return "", errors.New("cmd should provide")
  }

  return fmt.Sprintf("service %s", cmd), nil
}
```

使用 errors.New 函数可以构造一个 error  对象出来，不过这个对象用字符串表示结果，调用者很难去判断错误类型，所以更常见的做法是把错误的信息使用 var 定义错误并暴露到保外，重构一下代码:

```go
//ErrCmdMissing 命令缺失
var ErrCmdMissing = errors.New("cmd should provide")

func exchangeCommand2(cmd string) (string, error) {
  if len(cmd) == 0 {
    return "", ErrCmdMissing
  }

  return fmt.Sprintf("service %s", cmd), nil
}
```

现在调用者可以使用包内的 ErrCmdMissing 来做与判断了，不用纠结于具体的字符串内容是什么。


对于有些严重的错误如果想直接停止程序运行，可以调用内置函数 panic 可以终止，以空字符串为参数来调用下面的函数，程序会终止退出。

```go
func exchangeCommand3(cmd string) string {
  if len(cmd) == 0 {
    panic(ErrCmdMissing)
  }

  return fmt.Sprintf("service %s", cmd)
}
```

运行后提示错误，panic: cmd should provide，随机程序终止。问题是在程序退出之前，往往需要做一些清理操作，或者记录一些日志，甚至是想让代码继续运行，有没有挽救的方法呢? 有，recover 函数可以捕获错误，但是它必须工作在 defer 中。

```go
func exchangeCommand4(cmd string) string {
  defer func() {
    if err := recover(); err != nil {
      if err == ErrCmdMissing {
        // 该错误不太重要，记录一下不管它
        fmt.Println(err)
      } else {
        // 其他的错误就致命了
        panic(err)
      }
    }
  }()

  if len(cmd) == 0 {
    panic(ErrCmdMissing)
  }

  if cmd == "gameover" {
    panic(ErrGameOver)
  }

  return fmt.Sprintf("service %s", cmd)
}
```

在 recover 中还能继续使用 panic 终止执行，但是 panic 的作用域是函数级别，跨协程是不会影响的，关于协程的知识将在并发的章节学习。


如果错误只能可能是一种，那么 err 的返回值其实可以简单的是一个 bool 类型，比如前面的章节当从 map 结构查询字典的时候:

```go
// val, ok := dict["one"]
if val, ok := dict["one"]; ok {
  // 找到了 one 放心返回
  return val 
}
```

函数的最后一个参数 error 的范式是 go 语言的特色，也有很多人觉得它设计的太简陋了，因为 error 接口只包含了一段字符串的错误信息，为此常常需要自定义 error 类型，或者把 error 类型嵌套到自己的结构体中，不过如果你遇到 error 不想处理的情况，可以直接把 error 当作本函数的错误返回给上一层调用者，这就是 error 的链式传递。


本章节的代码 [https://github.com/developdeveloper/go-demo/tree/master/10-error-handler](https://github.com/developdeveloper/go-demo/tree/master/10-error-handler)
